//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCTesting.Models.AllOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestingOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestingOrder()
        {
            this.TestingOrderDetails = new HashSet<TestingOrderDetail>();
        }
    
        public int orderID { get; set; }
        public string orderName { get; set; }
        public string statusText { get; set; }
        public Nullable<int> status { get; set; }
        public string payMethod { get; set; }
        public Nullable<double> totalPay { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string cusName { get; set; }
        public string address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestingOrderDetail> TestingOrderDetails { get; set; }
    }
}
