//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCTesting.Models.AllOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestingOrderDetail
    {
        public int orderID { get; set; }
        public int proID { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> totalPrice { get; set; }
    
        public virtual TestingOrder TestingOrder { get; set; }
    }
}
