//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCTesting.Models.AllOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestingTempOrder
    {
        public int tempID { get; set; }
        public Nullable<int> cusID { get; set; }
        public Nullable<int> proID { get; set; }
        public Nullable<int> quantity { get; set; }
    }
}
