//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVCTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestingProduct
    {
        public int proID { get; set; }
        public string proName { get; set; }
        public string proImg { get; set; }
        public string proDesc { get; set; }
        public int quantity { get; set; }
        public double priceDeli { get; set; }
        public double priceReceived { get; set; }
        public Nullable<System.DateTime> dateReceive { get; set; }
        public Nullable<System.DateTime> dateDeli { get; set; }
    }
}
